### ISSUE TITLE
Set different cache maxAges with redux-bundler

### ISSUE THREAD

**Issue by aulneau** [HenrikJoreteg/money-clip#1]
Hey there! First off wanted to say that I am loving redux bundler and money clip :)

I have various actions that I would prefer to persist longer than others, what would be the best way to accomplish that? I have a structure similar in the various example apps using redux bundler with money clip, eg using:

```js

// cache.js
export default getConfiguredCache({
  maxAge: 1000 * 60 * 60,
  version: 1
});


// bundles/index.js

export default composeBundles(
  ...
  createCacheBundle(cache.set),
  extraArgs
);
```

**Comment by HenrikJoreteg** [comment]
@aulneau glad you're enjoying things so far. 

You've got a couple of choices. First of all, the thing to understand is the cache doesn't self-expire. So the max age is determined by the "read" operation not the `set()` which means that when your app boots up you could opt to use `get()` instead of `getAll()` to get keys individually and specify desired max age for each one. If you were doing that, you probably wouldn't use the `getConfiguredCache` helper for the read operation, but as long as both have the same `version` it doesn't matter.

The other options is to leave the cache stuff as is, but use something like `createAsyncResourceBundle` to expire the content faster and us it to specify max acceptable age: https://reduxbundler.com/api/included-bundles.html#createcachebundlecachingfunction

You can see an example of the fine-grained age control you can accomplish with that in this demo: https://codesandbox.io/s/qlz03qyn0q

**Comment by HenrikJoreteg** [comment]
I'm going to close this, assuming it's handled. Feel free to re-open if not.
